# 重铸音效设置
reforge_sound:
  start: minecraft:entity.villager.work_weaponsmith
  anim: minecraft:block.smithing_table.use
  done: minecraft:block.anvil.use

# GUI 相关设置
gui:
  layout:
    - "# # # # # # # # #"
    - "# # i # o # c # #"
    - "# # # # # # # # #"
    - "# # u u u u u # #"
    - "# # u u u u u # #"
    - "# # # # # # # # #"
